-- ============================================
-- LIFE PET - MIGRATION V1
-- Criação das tabelas
-- ============================================

-- TABELA TUTOR
CREATE TABLE tutor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    telefone VARCHAR(255) NOT NULL
);

-- TABELA PET
CREATE TABLE pet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    idade INTEGER NOT NULL,
    raca VARCHAR(255) NOT NULL,
    especie VARCHAR(255) NOT NULL,
    peso DOUBLE NOT NULL,
    tutor_id BIGINT,

    CONSTRAINT fk_pet_tutor
        FOREIGN KEY (tutor_id)
        REFERENCES tutor(id)
);

-- TABELA CONSULTA
CREATE TABLE consulta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    veterinario VARCHAR(255) NOT NULL,
    observacoes VARCHAR(255) NOT NULL,
    pet_id BIGINT,

    CONSTRAINT fk_consulta_pet
        FOREIGN KEY (pet_id)
        REFERENCES pet(id)
);

-- TABELA VACINA
CREATE TABLE vacina (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    data_aplicacao DATE NOT NULL,
    proxima_dose DATE NOT NULL,
    pet_id BIGINT,

    CONSTRAINT fk_vacina_pet
        FOREIGN KEY (pet_id)
        REFERENCES pet(id)
);

-- TABELA MEDICAMENTO
CREATE TABLE medicamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    dosagem VARCHAR(255) NOT NULL,
    frequencia VARCHAR(255) NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    pet_id BIGINT,

    CONSTRAINT fk_medicamento_pet
        FOREIGN KEY (pet_id)
        REFERENCES pet(id)
);

-- TABELA HISTORICO
CREATE TABLE historico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(255) NOT NULL,
    data_registro DATE NOT NULL,
    observacoes VARCHAR(255),
    pet_id BIGINT,

    CONSTRAINT fk_historico_pet
        FOREIGN KEY (pet_id)
        REFERENCES pet(id)
);